name: e2e

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        python-version: [3.8]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Makemigrations and Migrate
      working-directory: server
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run server in background
      working-directory: server
      run: |
        python manage.py runserver &

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run e2e tests
      working-directory: client
      env:
        NODE_ENV: test
      run: |
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        apt-get -qq update -y
        apt-get -qq install -y --allow-unauthenticated google-chrome-stable xvfb gtk2-engines-pixbuf xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable imagemagick x11-apps default-jre
        Xvfb :0 -ac -screen 0 1024x768x24 &
        export DISPLAY=:99
        ln -s ../../../native_client/app/core/ web_client/src/app/core
        cd web_client
        npm install -silent --unsafe-perm -g @angular/cli@1.1.2
        npm install --silent
        node ./node_modules/.bin/webdriver-manager update
        ng e2e --protractorConfig=protractor.conf.js

